### ISSUE TITLE
Installing on R-studio running R 3.2.1

### ISSUE THREAD

**Issue by Hergie** [yutannihilation/estatapi#14]
Hi,
When trying to install the package using the aforementioned set-up (institutional computer), I get error messages and the installation is unsuccessful.

```
install.packages('estatapi')
```

yields:

> Warning in install.packages :
> package ‘estatapi’ is not available (as a binary package for R version 3.2.1)

Alternatively `devtools::install_github("yutannihilation/estatapi")` yields:

> Downloading GitHub repo yutannihilation/estatapi@master
> from URL https://api.github.com/repos/yutannihilation/estatapi/zipball/master
> Error in curl::curl_fetch_memory(url, handle = handle) : 
> Peer certificate cannot be authenticated with given CA certificates

What might be the issue?

**Comment by yutannihilation** [comment]
Thanks for the report.

Could you try install.package("estapapi", type = "source") ?
But I'm not sure if this works for R 3.2.1...

**Comment by Hergie** [comment]
Thanks for getting back. I suppose you mean 'estatapi' and not 'estapapi'?
However, both bring out an error message:

> Warning in install.packages :
>   cannot open compressed file
> '//ecnbwn06p/sw_dist/r_white_listed_packages/src/contrib/PACKAGES',
> probable reason 'No such file or directory'
> Error in install.packages : cannot open the connection

2016-07-06 10:55 GMT-04:00 yutannihilation notifications@github.com:

**Comment by yutannihilation** [comment]
Ah, sorry for the misspelling...Yes, `"estatapi"` is right. In my environment, I could successfully install:

``` r
install.packages("estatapi", type = "source")
#> Installing package into ‘C:/Users/user1/Documents/R/win-library/3.3’
#> (as ‘lib’ is unspecified)
#> trying URL 'https://cran.rstudio.com/src/contrib/estatapi_0.2.tar.gz'
#> Content type 'application/x-gzip' length 21314 bytes (20 KB)
#> downloaded 20 KB
#> 
#> * installing *source* package 'estatapi' ...
#> ** package 'estatapi' successfully unpacked and MD5 sums checked
#> ** R
#> ** preparing package for lazy loading
#> ** help
#> *** installing help indices
#> ** building package indices
#> ** testing if installed package can be loaded
#> *** arch - i386
#> *** arch - x64
#> * DONE (estatapi)
#> 
#> The downloaded source packages are in
#>  ‘C:\Users\user1\AppData\Local\Temp\RtmpI3O7UM\downloaded_packages’
```

**Comment by yutannihilation** [comment]
> r_white_listed_packages

Is it that you are allowed to install only white listed packages in your environment? I guess you'd better ask the system administrator about how to install R packages, or ask on StackOverflow, since I'm not sure this kind of environment, sorry :(

**Comment by Hergie** [comment]
I could install and load the package fine after having my system administrator install R 3.3.0 Thank you!

**Comment by yutannihilation** [comment]
Wow, congratulations! :+1:
