### ISSUE TITLE
Support API version 3.0

### ISSUE THREAD

**Issue by uribo** [yutannihilation/estatapi#24]
API version 3.0 has been released since July 26, 2019.
https://www.e-stat.go.jp/api/api-info/e-stat-manual3-0 (🇯🇵 Japanese)

**Comment by yutannihilation** [comment]
I don't remember well, but I think I didn't consider this high priority because I don't know how useful the new features are. Do you have any usage in your mind?

https://www.e-stat.go.jp/api/api-info/api-spec

（日本語でも大丈夫です）

**Comment by uribo** [comment]
うーん、確かに有用性はないのかもですね。
`collectArea`パラメータの使いどころがありそうだなという気はします。

ソースコードを見ていたらバージョンが2.1だったので気になったのでした。

**Comment by yutannihilation** [comment]
アップデートするためにはまずはestatapiをどうやって作ったか思い出さないといけなくて、それはけっこう大変そうで、その大変さに見合うメリットを見出せずにいる、という感じです。

easyestat で引き取ってくれても大丈夫ですよ！

**Comment by uribo** [comment]
e-StatのAPI、ちょっとややこしいですね。
easyestatはお試しかつ、estatapiに便乗しようという魂胆のパッケージなので...

**Comment by yutannihilation** [comment]
まあ今やればもうちょっときれいに書ける気がする、という思いはあるので手が空いたら（？）やってみます。

**Comment by yutannihilation** [comment]
何が違うようになったのかよくわかってないけどバージョン3.0に移行しました（なんか結果にカラムが増えた気がする）
